# Generated by packaging/homebrew/render-formula.sh. Do not edit by hand:
# the release workflow overwrites this file in the tap on every tag.
class AgentTop < Formula
  desc "htop for local coding agents: processes, subagents, MCP servers, tokens and cost"
  homepage "https://github.com/kannandreams/agent-top"
  version "0.19.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/kannandreams/agent-top/releases/download/v0.19.1/agent-top-v0.19.1-aarch64-apple-darwin.tar.gz"
      sha256 "67bae0743a6bf5919b824e1f2c31463379f1651c498da7aeaba1e817488b84d9"
    end
    on_intel do
      url "https://github.com/kannandreams/agent-top/releases/download/v0.19.1/agent-top-v0.19.1-x86_64-apple-darwin.tar.gz"
      sha256 "2abee0a867625704f2deea88a29ac551c7c3b2cf18ee34c91c62954de9f8743a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/kannandreams/agent-top/releases/download/v0.19.1/agent-top-v0.19.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "556aac912c3507387612345688b73282aaa8de638c155e72b7d72e38aef41fce"
    end
    on_intel do
      url "https://github.com/kannandreams/agent-top/releases/download/v0.19.1/agent-top-v0.19.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "ccb4f921927a52e8975535213c8d873af436f883cec23d17dae60077b285baea"
    end
  end

  def install
    bin.install "agent-top"
    # Tab completion for every flag, generated from the binary itself so it can
    # never drift from the CLI it describes.
    generate_completions_from_executable(bin/"agent-top", "--completions", shells: [:bash, :zsh, :fish])
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/agent-top --version")
    # Discovery must work on a machine with no agents running at all.
    assert_match "\"schema_version\"", shell_output("#{bin}/agent-top --json")
  end
end
