# Generated by packaging/homebrew/render-formula.sh. Do not edit by hand:
# the release workflow overwrites this file in the tap on every tag.
class AgentTop < Formula
  desc "htop for local coding agents: processes, subagents, MCP servers, tokens and cost"
  homepage "https://github.com/kannandreams/agent-top"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/kannandreams/agent-top/releases/download/v0.1.0/agent-top-v0.1.0-aarch64-apple-darwin.tar.gz"
      sha256 "0d8b3e7d22d4edd0c09fb6225821bb8e435b82e9498cbfd2aab461dcc1bdc79c"
    end
    on_intel do
      url "https://github.com/kannandreams/agent-top/releases/download/v0.1.0/agent-top-v0.1.0-x86_64-apple-darwin.tar.gz"
      sha256 "caef0a0ce8dbdaf52a88f505c8df56521d21da5d992358b0453e557b3e0e145c"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/kannandreams/agent-top/releases/download/v0.1.0/agent-top-v0.1.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "cb3100568b1627362646f931f9700a23c68e417a618c76b13960d6b557c29796"
    end
    on_intel do
      url "https://github.com/kannandreams/agent-top/releases/download/v0.1.0/agent-top-v0.1.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "49423555bd0327b4c6ab4022356e491bbfd29e69e39d55d98fb7485c9fe690e0"
    end
  end

  def install
    bin.install "agent-top"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/agent-top --version")
    # Discovery must work on a machine with no agents running at all.
    assert_match "\"schema_version\"", shell_output("#{bin}/agent-top --json")
  end
end
