# Generated by packaging/homebrew/render-formula.sh. Do not edit by hand:
# the release workflow overwrites this file in the tap on every tag.
class AgentTop < Formula
  desc "htop for local coding agents: processes, subagents, MCP servers, tokens and cost"
  homepage "https://github.com/kannandreams/agent-top"
  version "0.4.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/kannandreams/agent-top/releases/download/v0.4.0/agent-top-v0.4.0-aarch64-apple-darwin.tar.gz"
      sha256 "02b2bcd796c7f3bf16be0bf58f7cb4a031f0e6b0f84f42cb8965e6cb8a225016"
    end
    on_intel do
      url "https://github.com/kannandreams/agent-top/releases/download/v0.4.0/agent-top-v0.4.0-x86_64-apple-darwin.tar.gz"
      sha256 "b23f7a9209df287179ef61cf8eae2878d7843e7a2ad65ccd4a5fa71e112363a9"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/kannandreams/agent-top/releases/download/v0.4.0/agent-top-v0.4.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "ec492d1f5bcf2f47fb10d5a7d5b2c0cf9cda3427b140ee40fff65bec277e14b1"
    end
    on_intel do
      url "https://github.com/kannandreams/agent-top/releases/download/v0.4.0/agent-top-v0.4.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "ee417ee74e324f45c021469ef618b18907c6daca6e697dbe653e639fa50cedab"
    end
  end

  def install
    bin.install "agent-top"
    # Tab completion for every flag, generated from the binary itself so it can
    # never drift from the CLI it describes.
    generate_completions_from_executable(bin/"agent-top", "--completions", shells: [:bash, :zsh, :fish])
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/agent-top --version")
    # Discovery must work on a machine with no agents running at all.
    assert_match "\"schema_version\"", shell_output("#{bin}/agent-top --json")
  end
end
